// Generated by https://quicktype.io

export interface PeopleDetailsResponse {
    adult:                boolean;
    also_known_as:        string[];
    biography:            string;
    birthday:             null;
    deathday:             null;
    gender:               number;
    homepage:             null;
    id:                   number;
    imdb_id:              null;
    known_for_department: string;
    name:                 string;
    place_of_birth:       null;
    popularity:           number;
    profile_path:         null;
}